### ISSUE TITLE
Integration with Viper

### ISSUE THREAD

**Issue by marcellodesales** [golobby/container#22]
Hi there,

This is a great component to what I'm looking for... :) I'd like to integrate VIper with Container:

1. Users create configuration files, say in `yaml`
2. In order to load the properties, I'd like to have a strongly-typed representation using `structs` that directly maps to the files
3. As a developer, I'd like to get the singleton instance of this struct so I can use it

I'd like to do something similar to `ConfigurationProperties` of SpringBoot from https://docs.spring.io/spring-boot/docs/2.1.13.RELEASE/reference/html/boot-features-external-config.html

Has someone worked on something similar?

Thank you

**Comment by miladrahimi** [comment]
There is singleton binding supported in the package that you can bind a struct to itself.
https://github.com/golobby/container#singleton
