### ISSUE TITLE
Get the receiver/instance from the concrete / AutoBind based on tags

### ISSUE THREAD

**Issue by Cililing** [golobby/container#24]
Hi, I am working on a project where we use the container library.

We are trying to "tune" the usage of the DI container with custom tags, to get rid of call-chains like
```go
func NewInstance() *Instance {
    var repo repository.Notifications
    var bridge fcm.Bridge
    var timeProvider tp.TimeProvider

    main.DI.Make(&repo)
    main.DI.Make(&bridge)
    main.DI.Make(&timeProvider)

    // return instance...
}
```

What I want to do is to mark some struct fields with a custom tag, let's say `di:"inject"` to automatically inject the fields at some point (like `execute` call).

What I've already achieved is the following code:
```go
type Instance struct {
    context ctx.Context
    
    repo repository.Notifications `di:"bind"`
    ...
}

func inject(gc GoCase) {
	rv := reflect.ValueOf(gc).Elem()
	t := rv.Type()

	for i := 0; i < t.NumField(); i++ {
		field := t.Field(i)
		rvField := rv.Field(i)
		if value, ok := field.Tag.Lookup("di"); ok {
			if value == "bind" {

				y := reflect.NewAt(rvField.Type(), unsafe.Pointer(rvField.UnsafeAddr())).Elem()
				receiverType := y.Type()
				concrete, ok := DI[receiverType] // DI is the app-container
				if !ok {
					panic("concrete not found for the abstraction" + receiverType.String())
				}

				// Concrete found, but how do I get instance/receiver from the concrete?
				// Do I need to use the reflection here? Or maybe it's better to add/expose
				// a possibility to do that in the library?
				
				fmt.Print(concrete) // just for testing
			}
		}
	}
}
```

My wonderings are explained in the comment.

And I see a few possibilities:
* use reflection to find the concrete (doesn't sound good to me, to be honest)
* expose proper fields or add a proper method in the library (like `GetConcrete(Type)`)
* add an "extension" to the library that allows doing the bindings based on a tag, let's say `di:"inject"` (I can implement it, but first I would like to know what you think about it).
* or, maybe you see another way to do that? :)

Thanks for your input!

**Comment by miladrahimi** [comment]
I think if the `make()` method accepts structs and fills their fields with appropriate concretes from the container, it could be a nice feature. What's your opinion @amirrezaask?

**Comment by Cililing** [comment]
You mean `container.Make(receiver interface{})` should act differently depending on the parameter (interface/func/struct)? I am not convenient, I would prefer another method for this purpose (like `Bind()` or something).

**Comment by miladrahimi** [comment]
Since the `make()` method is already implemented for interfaces and functions, we can change it to support structs as well. But your idea about the methods with single responsibility is great. So we'll implement three methods for the three mentioned kinds and deprecate the `make()` method to be removed next major version.

**Comment by miladrahimi** [comment]
Dear @Cililing,
The new version https://github.com/golobby/container/releases/tag/v2.1.0 is released.
The new feature is described here:
https://github.com/golobby/container#using-structs

**Comment by Cililing** [comment]
Hi @miladrahimi , thanks for your support and your contribution. The feature looks really nice and I am going to test it right now.

I found some issues (I described them in a PR: https://github.com/golobby/container/pull/26#pullrequestreview-625176679 ). Please take a look ;)

Anyway, I think this issue is resolved - a library has a really nice feature. The code looks really simpler in some cases. Thank again, m8!
