### ISSUE TITLE
Enable to Get Error on Binding

### ISSUE THREAD

**Issue by forest1102** [golobby/container#32]
Hello, I am using your great library for Dependency injection.  
However, I want to retrieve errors when binding.  
For instance, my code below is to open SQLite DB, but when Opening DB failed, I have to call panic() to show an error. 

```go
container.Singleton(func() *gorm.DB {
		DBFile := "/tmp/test.db"
		dialector := sqlite.Open(DBFile)
		db, err := gorm.Open(dialector)

		if err != nil {
			panic(err)
		}

		return db.Debug()
	})
```

So, I want you to enable me to run the code like below to retrieve the error.  
Right now, when error occurs, the code below just cause nil reference error.

```go
container.Singleton(func() (*gorm.DB, error) {
		DBFile := "/tmp/test.db"
		dialector := sqlite.Open(DBFile)
		db, err := gorm.Open(dialector)

		if err != nil {
			return nil, err
		}

		return db.Debug(), nil
	})
```

Thanks,

**Comment by miladrahimi** [comment]
Hello @forest1102 
We support this kind of errors now:
https://github.com/golobby/container#resolver-errors
Please update the library and let us know if there is any other issue.

**Comment by forest1102** [comment]
Thanks A Lot! This is what I wanted.
