### ISSUE TITLE
Singleton always cast second parameter as error

### ISSUE THREAD

**Issue by iarkaroy** [golobby/container#35]
First of all, thanks for this amazing library.
Here is what my singleton call is like
```
container.Singleton(func() (*gorm.DB, error) {
        dbFile := "/tmp/test.db"
	dialector := sqlite.Open(dbFile)
	db, err := gorm.Open(dialector)

	if err != nil {
		return nil, err
	}

	return db.Debug(), nil
})
```
But I am always getting `panic: interface conversion: interface is nil, not error` even when error is nil.

I think there should be a check for nil before casting to error type in https://github.com/golobby/container/blob/800c8e19e5cc8d7e9471a1b9faf66367294d5e55/pkg/container/container.go#L74

Can you please look into it?

Thanks

**Comment by miladrahimi** [comment]
Please update to the new version
https://github.com/golobby/container/releases/tag/3.1.4
And let us know if your problem is resolved.

**Comment by iarkaroy** [comment]
Yes, the issue is fixed now. Thanks.
