### ISSUE TITLE
Singleton's are created twice when resolver returns (T, error)

### ISSUE THREAD

**Issue by Place1** [golobby/container#37]
i've added some example code below and i've found that the singleton is created twice.

```golang
c := container.New()

c.Singleton(func() (ExampleService, error) {
	fmt.Println("singleton created")
	return CreateExampleService()
})
```

the issue only occurs because the resolver function returns a 2-tuple of (ExampleService, error)

the issue is happening because of the invoke call happening in this loop (I think) https://github.com/golobby/container/blob/master/container.go#L101

**Comment by miladrahimi** [comment]
Thanks @Place1 for reporting the bug.
It must be fixed on: https://github.com/golobby/container/releases/tag/v3.1.7

**Comment by Place1** [comment]
Absolute legend. Thanks!
