### ISSUE TITLE
Possible outdated README documentaion

### ISSUE THREAD

**Issue by Pavel-Durov** [golobby/container#47]
I just installed the package and gave it a go. I was following the README code examples, but I got some type errors.
Installation:
```
$ go get github.com/golobby/container/v3
```
go.sum:
```
github.com/golobby/container v1.3.0 h1:Pgk8fK9fJHuZqU924Bl8+DY2/n9jCUtsSKfiOctdQ9A=
github.com/golobby/container v1.3.0/go.mod h1:6yAH4QK+Hi8HxGuCJuAGiqS/a5n8YP+4bXNpPdKzLVM=
github.com/golobby/container/v3 v3.3.0 h1:ohPSWUUY67yvOhIBVC9Wv1pnsh8iOwRS0U1M1bjKBG8=
github.com/golobby/container/v3 v3.3.0/go.mod h1:RDdKpnKpV1Of11PFBe7Dxc2C1k2KaLE4FD47FflAmj0=
```
My code following README example:
```go
type Test interface {
	Test()
}
type TestImpl struct {
}

func (iml *TestImpl) Test() {
	fmt.Println("Test")
}

func main() {
	// Bind Config interface to JsonConfig struct
	err := container.Singleton(func() Test {
		return &TestImpl{}
	})

	var c TestImpl
	err := container.Resolve(&c)
	// `c` will be the instance of JsonConfig
}
```
Errors:
> container.Singleton((func() Test literal)) (no value) used as valuecompiler[TooManyValues](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#TooManyValues)

> Resolve not declared by package containercompiler[UndeclaredImportedName](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#UndeclaredImportedName)

It looks like there:
 * Instead of resolve there's a Make function defined
 * sIngleton function doesn't return an error?
 
 Is it an issue with outdated documentation, or am I doing something weird here?

Thanks :)

**Comment by Pavel-Durov** [comment]
Ah I think I imported by default the wrong version:
```
import "github.com/golobby/container"
```
instead 
```
import "github.com/golobby/container/v3"
```

**Comment by miladrahimi** [comment]
Change `var c TestImpl` to `var c Test`.

**Comment by Pavel-Durov** [comment]
@miladrahimi that was a typo
but the actual issue was with the import :)

**Comment by Pavel-Durov** [comment]
I've created a small PR with a readme update if you find it useful
https://github.com/golobby/container/pull/48
